app:
  version: 0.0.1-SNAPSHOT


spring:
  application:
    name: hydro-flow
    version: 0.0.1-SNAPSHOT
    formatted-version: " (v${spring.application.version})"

  datasource:
    url: jdbc:postgresql://localhost:5433/hf_management
    username: admin
    password: admin

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

