spring:
  application:
    name: hydro-flow

  datasource:
    url: jdbc:postgresql://localhost:5433/hf_management
    username: admin
    password: admin

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

